### ISSUE TITLE
Attempting to build unitypackage errors on NullPointerException

### ISSUE THREAD

**Issue by LeeLorenzSr** [googlesamples/google-signin-unity#129]
Honestly, the last thing I wanted to do over the past three days is build this package to use in my Unity app. After finally getting it to accept the SDK and NDK installed on my system (which now has several installations scattered around), dealing with "NDK Not Configured" (had to include the location in the local.properties), I finally got it building, only to run into this.
`Consult IDE log for more details (Help | Show Log) (13 s 977 ms) 
2020-02-25 23:09:38,248 [  55609]   WARN - e.project.sync.GradleSyncState -  
java.lang.RuntimeException: 
	at com.android.tools.idea.gradle.project.sync.idea.ProjectSetUpTask.onFailure(ProjectSetUpTask.java:120)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.executeImpl(ExternalSystemUtil.java:576)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.lambda$execute$0(ExternalSystemUtil.java:388)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:149)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:388)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:649)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-02-25 23:09:38,319 [  55680]   INFO - roid.tools.ndk.GradleWorkspace - Updating model took 0.043s 
2020-02-25 23:09:38,680 [  56041]   INFO - ge.ExternalProjectsDataStorage - Save external projects data in 35 ms `

**Comment by QuadrivoSoftware** [comment]
Well, this is an adventure. Your gradle script doesn't like anything but Oracle's JDK. This is the most painful build I have had in quite a while... and my current job is upgrading/enhancing/fixing a legacy system comprised of hundreds of VB6 and .NET projects for 14k+ installs.

After installing the JDK, pointing a ton of variables to locations, updating local properties, updating PATH to find ninja.exe, and pointing the gradle script's hard coded unity.exe location to the correct place, I now end up with script errors.

This is the second machine I've tried performing this build on, a relatively clean system with fresh installs of pretty much everything. Latest Android Studio, with SDK 10.0, latest stable NDK, latest stable JDK... Unity 2019.2.6f1

Most of the Google Unity plugins have the unitypackage already built. Why not this one? I'd use the PlayServices plugin, but my Android app configuration is hosed on the Google API SErvices configuration (duplicate, bad entry preventing me from using the Android package SHA1, and it won't delete the bad entry). I kind of prefer using a consistent OAuth method across Android and iOS (and Play Services just decided to dump support for iOS anyway).

**Comment by LeeLorenzSr** [comment]
(Sorry for the confusion - my other laptop has a company Git account) 

I may try and copy in the binaries that were created, the srcaar files, as it looks like the only failure was assembling the assets into the unitypackage file. This isn't really a resolution to the ultimate problem, which is either poor build instructions or a poor build script (or possibly issues with the c# files, preventing a build of the unitypackage by unity.exe).

I also realize JDK and Android SDK/NDK issues are an eternal issue with running these tools in Windows, but it is no less problematic. Stackoverflow queries are less than helpful, much like the blind leading the blind.
