### ISSUE TITLE
crash on android

### ISSUE THREAD

**Issue by jaywang** [googlesamples/google-signin-unity#134]
`
anyone fixed this? Random crash andorid 6.0 5.0 when i invoke login function.

03-13 10:08:40.172  2341  2341 E AndroidRuntime: FATAL EXCEPTION: main
03-13 10:08:40.172  2341  2341 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
03-13 10:08:40.172  2341  2341 E AndroidRuntime: Unity version     : 2018.4.13f1
03-13 10:08:40.172  2341  2341 E AndroidRuntime: Device model      : Netease 
03-13 10:08:40.172  2341  2341 E AndroidRuntime:
03-13 10:08:40.172  2341  2341 E AndroidRuntime: Caused by: java.lang.RuntimeException: Window couldn't find content container view
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3915)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3199)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2508)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5539)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
03-13 10:08:40.172  2341  2341 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
`

**Comment by soniska22** [comment]
I ma having exactly the same issue.
