### ISSUE TITLE
Android TV screen goes black and doesn't switch back to the game after first login

### ISSUE THREAD

**Issue by anuragpapineni** [googlesamples/google-signin-unity#37]
This strangely doesn't happen on an Android TV emulator, only on actual devices. When I login for the first time and have to choose an account the screen just goes black afterward.

After choosing an account and closing the process the login appears to have worked upon launching the app again.

Replication Steps on Android TV:

1. Clear data of an app that signs into google on startup.
2. Launch the app and choose an account
3. The signin should appear to work, but the app is now just a black screen.
4. Close the app and launch again. It appears to be signed in

**Comment by pfleeter** [comment]
I see the same thing on Android devices.  I get an exception in my logs:

> I/Auth    (14852): [AddAccountTask] Added account successfully.
> I/CheckinUtil(14778): Classify the device as Phone.
> W/art     (  700): Long monitor contention event with owner method=boolean com.android.server.accounts.AccountManagerService.saveAuthTokenToDatabase(com.android.server.accounts.AccountManagerService$UserAccounts, android.accounts.Account, java.lang.String, java.lang.String) from AccountManagerService.java:1296 waiters=0 for 120ms
> I/Auth    (14852): [AddAccountTask] Delivering result.
> I/Auth    (14852): [AddAccountLoader] Got result: hly@11f97803
> E/HttpOperation(11418): [BatchDataFetchOperation: jnt] Unexpected exception
> E/HttpOperation(11418): java.io.IOException: Cannot obtain authentication token
> E/HttpOperation(11418): 	at kwo.a(PG:28)
> E/HttpOperation(11418): 	at kvm.p(PG:52)
> E/HttpOperation(11418): 	at kvi.a(PG:21)
> E/HttpOperation(11418): 	at jdx.call(PG:5)
> E/HttpOperation(11418): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> E/HttpOperation(11418): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/HttpOperation(11418): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/HttpOperation(11418): 	at java.lang.Thread.run(Thread.java:818)
> E/HttpOperation(11418): Caused by: java.io.IOException: Error on service connection.
> E/HttpOperation(11418): 	at egx.a(Unknown Source)
> E/HttpOperation(11418): 	at egx.a(Unknown Source)
> E/HttpOperation(11418): 	at egw.a(Unknown Source)
> E/HttpOperation(11418): 	at fys.a(PG:4)
> E/HttpOperation(11418): 	at kwk.a(PG:44)
> E/HttpOperation(11418): 	at kwk.a(PG:18)
> E/HttpOperation(11418): 	at kwo.a(PG:23)
> E/HttpOperation(11418): 	... 7 more
> E/HttpOperation(11418): Caused by: java.lang.InterruptedException
> E/HttpOperation(11418): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1197)
> E/HttpOperation(11418): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:306)
> E/HttpOperation(11418): 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:407)
> E/HttpOperation(11418): 	at epv.a(Unknown Source)
> E/HttpOperation(11418): 	... 14 more
> E/LoginManager(11418): Account update failed
> E/LoginManager(11418): java.io.IOException: Rpc failed
> E/LoginManager(11418): 	at jdt.a(PG:226)
> E/LoginManager(11418): 	at jdx.call(PG:7)
> E/LoginManager(11418): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> E/LoginManager(11418): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/LoginManager(11418): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/LoginManager(11418): 	at java.lang.Thread.run(Thread.java:818)
> E/LoginManager(11418): Caused by: java.io.IOException: Cannot obtain authentication token
> E/LoginManager(11418): 	at kwo.a(PG:28)
> E/LoginManager(11418): 	at kvm.p(PG:52)
> E/LoginManager(11418): 	at kvi.a(PG:21)
> E/LoginManager(11418): 	at jdx.call(PG:5)
> E/LoginManager(11418): 	... 4 more
> E/LoginManager(11418): Caused by: java.io.IOException: Error on service connection.
> E/LoginManager(11418): 	at egx.a(Unknown Source)
> E/LoginManager(11418): 	at egx.a(Unknown Source)
> E/LoginManager(11418): 	at egw.a(Unknown Source)
> E/LoginManager(11418): 	at fys.a(PG:4)
> E/LoginManager(11418): 	at kwk.a(PG:44)
> E/LoginManager(11418): 	at kwk.a(PG:18)
> E/LoginManager(11418): 	at kwo.a(PG:23)
> E/LoginManager(11418): 	... 7 more
> E/LoginManager(11418): Caused by: java.lang.InterruptedException
> E/LoginManager(11418): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1197)
> E/LoginManager(11418): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:306)
> E/LoginManager(11418): 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:407)
> E/LoginManager(11418): 	at epv.a(Unknown Source)
> E/LoginManager(11418): 	... 14 more

**Comment by anuragpapineni** [comment]
If this is happening to you on phones I don't think it's the same issue. This only appears to be on Android TV for me and only on the latest Play Services version. I even wrote my own Google sign in plugin and it had the same problem.

I'd try downgrading Google Play Services on whatever device you're using. If that doesn't work you're probably having a different problem.

I think the issue I'm having is linked to this one:

https://issuetracker.google.com/issues/75238653
