### ISSUE TITLE
DllNotFoundException: native-googlesignin

### ISSUE THREAD

**Issue by jeeteshb** [googlesamples/google-signin-unity#50]
I was getting the below error when I used the google signin plugin for Unity Android.  I have imported the plugin multiple times but still getting DllNotFoundException.

at (wrapper managed-to-native) Google.Impl.GoogleSignInImpl:GoogleSignIn_Create (intptr)
07-04 08:50:29.338 30138 30179 E Unity   :   at Google.Impl.GoogleSignInImpl..ctor (Google.GoogleSignInConfiguration configuration) [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at Google.GoogleSignIn.get_DefaultInstance () [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at SignInSample.SigninSampleScript.OnSignIn () [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at UnityEngine.Events.InvokableCall.Invoke () [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at UnityEngine.UI.Button.Press () [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <filename unknown>:0 
07-04 08:50:29.338 30138 30179 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickH

**Comment by jeeteshb** [comment]
Failed to fetch the following dependencies:
com.google.android.gms:play-services-analytics-impl:15.0.1
com.google.android.gms:play-services-analytics:15.0.1
com.google.android.gms:play-services-tagmanager-v4-impl:15.0.1

**Comment by Syrlander** [comment]
Have you made sure to run the resolver under Assets in the top menu bar? It seems like you're missing some dependencies generated by the resolver.

**Comment by jeeteshb** [comment]
I have run the resolver from the Assets menu and it successfully resolved the dependencies but after creating the build I got below errors in adb logcat. 

Unable to lookup library path for 'native-googlesignin', native render plugin support disabled.
07-09 10:52:27.952  8977  9016 E Unity   : Unable to find native-googlesignin
07-09 10:52:28.000  8977  9016 E Unity   : DllNotFoundException: native-googlesignin

When I have done force resloved from Assets menu I got the below errors

Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-analytics-impl:15.0.1
com.google.android.gms:play-services-analytics:15.0.1
com.google.android.gms:play-services-tagmanager-v4-impl:15.0.1

**Comment by jeeteshb** [comment]
This is resolved now. I was directly copy pasting the  google-signin-unity project after downloading it from github and not installing the package google-signin-plugin-1.0.3.unitypackage from https://github.com/googlesamples/google-signin-unity/releases.

Thanks

**Comment by jeeteshb** [comment]
Getting this error on android project again.

AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.analytics.GoogleAnalytics
08-06 14:16:25.172 27556 27591 E Unity   : java.lang.ClassNotFoundException: com.google.android.gms.analytics.GoogleAnalytics
08-06 14:16:25.172 27556 27591 E Unity   : 	at java.lang.Class.classForName(Native Method)
08-06 14:16:25.172 27556 27591 E Unity   : 	at java.lang.Class.forName(Class.java:400)
08-06 14:16:25.172 27556 27591 E Unity   : 	at java.lang.Class.forName(Class.java:326)
08-06 14:16:25.172 27556 27591 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-06 14:16:25.172 27556 27591 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
08-06 14:16:25.172 27556 27591 E Unity   : 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
08-06 14:16:25.172 27556 27591 E Unity   : 	at android.os.MessageQueue.next(MessageQueue.java:392)
08-06 14:16:25.172 27556 27591 E Unity   : 	at android.os.Looper.loop(Looper.java:136)
08-06 14:16:25.172 27556 27591 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)

I have resolved the dependencies from PlayServiceResolver->AndroidResolver->Resolve/ Force Resolve but still getting the above error after calling googleAnalytics.LogEvent() function.
