### ISSUE TITLE
Google Play Store issue

### ISSUE THREAD

**Issue by Ryu17** [googlesamples/google-signin-unity#58]
MY PROBLEM :
Google Sign-in worked fine before uploading my app to the Google Play Store. However, if you upload your app to the Google Play Store and download the app from the Store and try Google Sign-in, you will not be able to sign in.

In logcat, I see the following error message:

`09-11 13:18:01.031  3480  3597 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{cfe9fb8 u0 com.google.android.gms/.auth.api.signin.ui.SignInActivity t592} time:85403509
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: Failed to instantiate custom view inflater androidx.appcompat.app.AppCompatViewInflater. Falling back to default.
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: java.lang.ClassNotFoundException: androidx.appcompat.app.AppCompatViewInflater
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at java.lang.Class.classForName(Native Method)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at java.lang.Class.forName(Class.java:324)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at java.lang.Class.forName(Class.java:285)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.support.v7.app.AppCompatDelegateImpl.a(:com.google.android.gms@12874023@12.8.74 (040400-204998136):1)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(:com.google.android.gms@12874023@12.8.74 (040400-204998136):1)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:758)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4593)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4668)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2248)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.support.v7.app.AppCompatDelegateImpl.o(:com.google.android.gms@12874023@12.8.74 (040400-204998136):9)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.support.v7.app.AppCompatDelegateImpl.c(:com.google.android.gms@12874023@12.8.74 (040400-204998136):1)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at ddp.onPostCreate(:com.google.android.gms@12874023@12.8.74 (040400-204998136))
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at com.google.android.chimera.Activity.publicOnPostCreate(:com.google.android.gms@12874023@12.8.74 (040400-204998136))
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at ddu.onPostCreate(:com.google.android.gms@12874023@12.8.74 (040400-204998136):3)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1216)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3236)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.os.Looper.loop(Looper.java:158)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.app.AppCompatViewInflater" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-2/lib/arm64, /data/app/com.google.android.gms-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	... 29 more
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	Suppressed: java.lang.ClassNotFoundException: androidx.appcompat.app.AppCompatViewInflater
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 		at java.lang.Class.classForName(Native Method)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 		... 30 more
09-11 13:18:01.041 17853 17853 I AppCompatDelegate: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

Has anyone experienced a similar problem?

**Comment by jonavuka** [comment]
I am having the same issue now, once I release the whole thing fails... When I build and install locally it's fine

**Comment by Ryu17** [comment]
I solved this problem. Did you use Google Play App Signing to register your app with Google Play Console? There are two SHA-1 values for uploading and for signing. Try changing the SHA-1 value.

**Comment by Ryu17** [comment]
> I am having the same issue now, once I release the whole thing fails... When I build and install locally it's fine

I solved this problem. Did you use Google Play App Signing to register your app with Google Play Console? There are two SHA-1 values for uploading and for signing. Try changing the SHA-1 value.

**Comment by jonavuka** [comment]
Thanks you're right about the SHA-1. However, for those using firebase with this plugin just link your app (with the google play store link) in the firebase console which will update the SHA-1 in the firebase project. If it doesn't update just add it in the firebase project manually yourself. Basically there should be both SHAs in the firebase project the upload SHA-1 and the app signing SHA-1

**Comment by derwaldgeist** [comment]
I noticed that when you are using Android Bundles and let Google Play Store sign your app, the SHA-1 key is not valid for the app in the app store anymore. I had to setup another Android App in the Google console, using the SHA-1 you can find in Play Store.
